routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'TokenCheck'])->group(function () {
    Route::get('/home', 'HomeController@index')->middleware('verified');
});

Route::middleware(['logging'])->group(function () {
    Route::resource('salesmanManagements', 'SalesmanManagementController');

    Route::resource('landlordManagements', 'LandlordManagementController');

    Route::resource('tenantManagements', 'TenantManagementController');
    Route::get('/tenantManagements/export/{id}', 'TenantManagementController@generateT');

    Route::resource('businessManagements', 'business_managementController');

    Route::resource('buildingManagements', 'BuildingManagementController');
    Route::get('/buildingManagements/export/{id}', 'BuildingManagementController@generateT');

    Route::resource('contracts', 'contractController');
    Route::get('mixed', 'contractController@mixedTable')->name('mixedTable');

    Route::resource('fixHistories', 'FixHistoryController');

    Route::resource('returnFormats', 'ReturnFormatController');

    Route::resource('banks', 'BankController');

    Route::resource('transactionDetails', 'TransactionDetailsController');

    Route::resource('lineConfigs', 'LineConfigController');

    Route::resource('logHistories', 'LogHistoryController');
});

Route::get('buildmag/download', 'BuildingManagementController@generateBill');

Route::get('returnFormat/download', 'ReturnFormatController@generateData');
Route::get('bank/download', 'BankController@generateData');
Route::get('mixed/download', 'contractController@generateMixedData');

Route::post('import/build', 'BuildingManagementController@import_build');

Route::post('contracts/UploadExcel', 'contractController@UploadExcel');

Route::post('landlordManagements/UploadExcel', 'LandlordManagementController@UploadExcel');

Route::post('tenantManagements/UploadExcel', 'TenantManagementController@UploadExcel');

Route::post('buildingManagements/UploadExcel', 'BuildingManagementController@UploadExcel');

Route::get('batch_upload', function () {
    return view('batch_upload');
});

Route::get('reward', 'HomeController@reward');

Route::get('glogin', array('as' => 'glogin', 'uses' => 'HomeController@googleLogin'));


Route::resource('users', 'UserController');

Route::resource('housePayHistories', 'HousePayHistoryController');


Route::resource('buildingManagementNews', 'building_management_newController');

Route::resource('cities', 'cityController');

Route::resource('cityAreas', 'city_areaController');

Route::resource('streets', 'streetController');

Route::resource('locatedLots', 'located_lotController');

Route::resource('contractsNews', 'contracts_newController');

Route::resource('contractsNews', 'contracts_newController');

Route::resource('contractsNews', 'contracts_newController');

Route::resource('buildingManagementNews', 'building_management_newController');

Route::resource('tenantManagementNews', 'tenant_management_newController');

Route::resource('matchManagements', 'match_managementController');

Route::get('contractManagements/create/{match_id}', 'contract_managementController@create');

Route::resource('contractManagements', 'contract_managementController');

// 以下為練習圖片上傳的玩具
Route::get('img_uploads', 'ImageController@index');
Route::get('images', 'ImageController@show');
Route::get('upload', 'ImageController@store');


Route::resource('cityAreas', 'city_areaController');


Route::resource('locatedLots', 'located_lotController');

Route::resource('fileManagments', 'file_managmentController');

Route::resource('changeHistories', 'change_historyController');

Route::resource('tenantFamilyInfos', 'tenant_family_infoController');

Route::resource('tenantMinorOffsprings', 'tenant_minor_offspringController');

Route::resource('tenantBuildingInfos', 'tenant_building_infoController');


Route::resource('insuranceManagements', 'insurance_managementController');

Route::resource('salesmanManagements', 'salesman_managementController');

Route::resource('insuranceManagements', 'insurance_managementController');


Route::resource('fixManagements', 'fix_managementController');

Route::resource('fixDetailManagements', 'fix_detail_managementController');

app/Models/LineConfig.php
<?php

namespace App\Models;

use DateTimeInterface;
use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class LineConfig
 * @package App\Models
 * @version May 27, 2021, 2:34 pm UTC
 *
 * @property string $name
 * @property string $val
 * @property string $nickname
 */
class LineConfig extends Model
{
    use SoftDeletes;

    public $table = 'line_configs';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'val',
        'nickname'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'val' => 'string',
        'nickname' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];





    /**
     * Prepare a date for array / JSON serialization.
     *
     * @param  \DateTimeInterface  $date
     * @return string
     */
    protected function serializeDate(DateTimeInterface $date)
    {
        return ((int)$date->format('Y') - 1911) . $date->format('-m-d H:i:s');
    }

}

app/Http/Controllers/LineConfigController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\LineConfigDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateLineConfigRequest;
use App\Http\Requests\UpdateLineConfigRequest;
use App\Repositories\LineConfigRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class LineConfigController extends AppBaseController
{
    /** @var  LineConfigRepository */
    private $lineConfigRepository;

    public function __construct(LineConfigRepository $lineConfigRepo)
    {
        $this->lineConfigRepository = $lineConfigRepo;
    }

    /**
     * Display a listing of the LineConfig.
     *
     * @param LineConfigDataTable $lineConfigDataTable
     * @return Response
     */
    public function index(LineConfigDataTable $lineConfigDataTable)
    {
        return $lineConfigDataTable->render('line_configs.index');
    }

    /**
     * Show the form for creating a new LineConfig.
     *
     * @return Response
     */
    public function create()
    {
        return view('line_configs.create');
    }

    /**
     * Store a newly created LineConfig in storage.
     *
     * @param CreateLineConfigRequest $request
     *
     * @return Response
     */
    public function store(CreateLineConfigRequest $request)
    {
        $input = $request->all();

        $lineConfig = $this->lineConfigRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/lineConfigs.singular')]));

        return redirect(route('lineConfigs.index'));
    }

    /**
     * Display the specified LineConfig.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $lineConfig = $this->lineConfigRepository->find($id);

        if (empty($lineConfig)) {
            Flash::error(__('messages.not_found', ['model' => __('models/lineConfigs.singular')]));

            return redirect(route('lineConfigs.index'));
        }

        return view('line_configs.show')->with('lineConfig', $lineConfig);
    }

    /**
     * Show the form for editing the specified LineConfig.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $lineConfig = $this->lineConfigRepository->find($id);

        if (empty($lineConfig)) {
            Flash::error(__('messages.not_found', ['model' => __('models/lineConfigs.singular')]));

            return redirect(route('lineConfigs.index'));
        }

        return view('line_configs.edit')->with('lineConfig', $lineConfig);
    }

    /**
     * Update the specified LineConfig in storage.
     *
     * @param  int              $id
     * @param UpdateLineConfigRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateLineConfigRequest $request)
    {
        $lineConfig = $this->lineConfigRepository->find($id);

        if (empty($lineConfig)) {
            Flash::error(__('messages.not_found', ['model' => __('models/lineConfigs.singular')]));

            return redirect(route('lineConfigs.index'));
        }

        $lineConfig = $this->lineConfigRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/lineConfigs.singular')]));

        return redirect(route('lineConfigs.index'));
    }

    /**
     * Remove the specified LineConfig from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $lineConfig = $this->lineConfigRepository->find($id);

        if (empty($lineConfig)) {
            Flash::error(__('messages.not_found', ['model' => __('models/lineConfigs.singular')]));

            return redirect(route('lineConfigs.index'));
        }

        $this->lineConfigRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/lineConfigs.singular')]));

        return redirect(route('lineConfigs.index'));
    }

    public function file_upload($file)
    {
        return Storage::put(storage_path('LineConfig'), $file);

    }

}

resources/views/line_configs/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid container-fixed-lg">
        <h3 class="page-title">
            @lang('models/lineConfigs.singular')
        </h3>
    </div>
    <div class="container-fluid container-fixed-lg">
        @include('adminlte-templates::common.errors')
        <div class="card card-transparent">
            <div class="card-body">
                <div class="row">
                    {!! Form::open(['route' => 'lineConfigs.store']) !!}

                        @include('line_configs.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/line_configs/datatables_actions.blade.php
{!! Form::open(['route' => ['lineConfigs.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('lineConfigs.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => 'return confirm("'.__('crud.are_you_sure').'")'
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/line_configs/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid container-fixed-lg">
        <h3 class="page-title">
            @lang('models/lineConfigs.singular')
        </h3>
    </div>
    <div class="container-fluid container-fixed-lg">
        @include('adminlte-templates::common.errors')
        <div class="card card-transparent">
            <div class="card-body">
                <div class="row">
                    {!! Form::model($lineConfig, ['route' => ['lineConfigs.update', $lineConfig->id], 'method' => 'patch']) !!}

                            @include('line_configs.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/line_configs/fields.blade.php
<div class="row">
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/lineConfigs.fields.name').':') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Val Field -->
<div class="form-group col-sm-6">
    {!! Form::label('val', __('models/lineConfigs.fields.val').':') !!}
    {!! Form::text('val', null, ['class' => 'form-control']) !!}
</div>

<!-- Nickname Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nickname', __('models/lineConfigs.fields.nickname').':') !!}
    {!! Form::text('nickname', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('lineConfigs.index') }}" class="btn btn-default">@lang('crud.cancel')</a>
</div>
</div>

resources/views/line_configs/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid container-fixed-lg">
        <h3 class="page-title">@lang('models/lineConfigs.plural')</h3>
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px;z-index: 100" href="{{ route('lineConfigs.create') }}">@lang('crud.add_new')</a>
    </div>
    <div class="container-fluid container-fixed-lg">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('line_configs.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/line_configs/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid   container-fixed-lg">
        <h3 class="page-title">
            @lang('models/lineConfigs.singular')
        </h3>
    </div>
    <div class="container-fluid   container-fixed-lg">
        <div class="card card-transparent">
            <div class="card-body">
                <div class="row" style="padding-left: 20px">
                    @include('line_configs.show_fields')
                    <a href="{{ route('lineConfigs.index') }}" class="btn btn-default">
                        @lang('crud.back')
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/line_configs/show_fields.blade.php
<!-- Name Field -->
<div class="form-group col-12">
    {!! Form::label('name', __('models/lineConfigs.fields.name').':') !!}
    <p>{{ $lineConfig->name }}</p>
</div>


<!-- Val Field -->
<div class="form-group col-12">
    {!! Form::label('val', __('models/lineConfigs.fields.val').':') !!}
    <p>{{ $lineConfig->val }}</p>
</div>


<!-- Nickname Field -->
<div class="form-group col-12">
    {!! Form::label('nickname', __('models/lineConfigs.fields.nickname').':') !!}
    <p>{{ $lineConfig->nickname }}</p>
</div>


<!-- Created At Field -->
<div class="form-group col-12">
    {!! Form::label('created_at', __('models/lineConfigs.fields.created_at').':') !!}
    <p>{{ $lineConfig->created_at }}</p>
</div>


<!-- Updated At Field -->
<div class="form-group col-12">
    {!! Form::label('updated_at', __('models/lineConfigs.fields.updated_at').':') !!}
    <p>{{ $lineConfig->updated_at }}</p>
</div>

resources/views/line_configs/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush