routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'TokenCheck'])->group(function () {
    Route::get('/home', 'HomeController@index')->middleware('verified');
});

Route::middleware(['logging'])->group(function () {
    Route::resource('salesmanManagements', 'SalesmanManagementController');

    Route::resource('landlordManagements', 'LandlordManagementController');

    Route::resource('tenantManagements', 'TenantManagementController');
    Route::get('/tenantManagements/export/{id}', 'TenantManagementController@generateT');

    Route::resource('businessManagements', 'business_managementController');

    Route::resource('buildingManagements', 'BuildingManagementController');
    Route::get('/buildingManagements/export/{id}', 'BuildingManagementController@generateT');

    Route::resource('contracts', 'contractController');
    Route::get('mixed', 'contractController@mixedTable')->name('mixedTable');

    Route::resource('fixHistories', 'FixHistoryController');

    Route::resource('returnFormats', 'ReturnFormatController');

    Route::resource('banks', 'BankController');

    Route::resource('transactionDetails', 'TransactionDetailsController');

    Route::resource('lineConfigs', 'LineConfigController');

    Route::resource('logHistories', 'LogHistoryController');
});

Route::get('buildmag/download', 'BuildingManagementController@generateBill');

Route::get('returnFormat/download', 'ReturnFormatController@generateData');
Route::get('bank/download', 'BankController@generateData');
Route::get('mixed/download', 'contractController@generateMixedData');

Route::post('import/build', 'BuildingManagementController@import_build');

Route::post('contracts/UploadExcel', 'contractController@UploadExcel');

Route::post('landlordManagements/UploadExcel', 'LandlordManagementController@UploadExcel');

Route::post('tenantManagements/UploadExcel', 'TenantManagementController@UploadExcel');

Route::post('buildingManagements/UploadExcel', 'BuildingManagementController@UploadExcel');

Route::get('batch_upload', function () {
    return view('batch_upload');
});

Route::get('reward', 'HomeController@reward');

Route::get('glogin', array('as' => 'glogin', 'uses' => 'HomeController@googleLogin'));


Route::resource('users', 'UserController');

Route::resource('housePayHistories', 'HousePayHistoryController');


Route::resource('buildingManagementNews', 'building_management_newController');

Route::resource('cities', 'cityController');

Route::resource('cityAreas', 'city_areaController');

Route::resource('streets', 'streetController');

Route::resource('locatedLots', 'located_lotController');

Route::resource('contractsNews', 'contracts_newController');

Route::resource('contractsNews', 'contracts_newController');

Route::resource('contractsNews', 'contracts_newController');

Route::resource('buildingManagementNews', 'building_management_newController');

Route::resource('tenantManagementNews', 'tenant_management_newController');

Route::resource('matchManagements', 'match_managementController');

Route::get('contractManagements/create/{match_id}', 'contract_managementController@create');

Route::resource('contractManagements', 'contract_managementController');

// 以下為練習圖片上傳的玩具
Route::get('img_uploads', 'ImageController@index');
Route::get('images', 'ImageController@show');
Route::get('upload', 'ImageController@store');


Route::resource('cityAreas', 'city_areaController');


Route::resource('locatedLots', 'located_lotController');

Route::resource('fileManagments', 'file_managmentController');

Route::resource('changeHistories', 'change_historyController');

Route::resource('tenantFamilyInfos', 'tenant_family_infoController');

Route::resource('tenantMinorOffsprings', 'tenant_minor_offspringController');

Route::resource('tenantBuildingInfos', 'tenant_building_infoController');


Route::resource('insuranceManagements', 'insurance_managementController');

Route::resource('salesmanManagements', 'salesman_managementController');

Route::resource('insuranceManagements', 'insurance_managementController');


Route::resource('fixManagements', 'fix_managementController');

Route::resource('fixDetailManagements', 'fix_detail_managementController');

app/Http/Controllers/BuildingManagementController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\BuildingManagementDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateBuildingManagementRequest;
use App\Http\Requests\UpdateBuildingManagementRequest;
use App\Models\BuildingManagement;
use App\Repositories\BuildingManagementRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Facades\Excel;
use Maatwebsite\Excel\Concerns\FromArray;
use Illuminate\Http\Request;
use Response;
use App\Models\TransactionDetails;

class BillExport implements FromArray
{
    protected $ary;
    function __construct($array)
    {
        $this->ary = $array;
    }
    public function array(): array
    {
        return $this->ary;
    }
}

class bExport implements FromArray, WithEvents
{
    protected $ary;
    function __construct($array)
    {
        $this->ary = $array;
    }
    public function array(): array
    {
        return $this->ary;
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function ($event) {
                //設定區域單元格垂直居中
                $event->sheet->getDelegate()->getStyle('A1:Z1265')->getAlignment()->setVertical('center');
                //設定區域單元格字型、顏色、背景等，其他設定請檢視 applyFromArray 方法，提供了註釋
                $event->sheet->getDelegate()->getStyle('A1:Z1')->applyFromArray([
                    'font' => [
                        'name' => 'Arial',
                        'bold' => true,
                        'italic' => false,
                        'strikethrough' => false,
                        'color' => [
                            'rgb' => 'FFFFFF'
                        ]
                    ],
                    'fill' => [
                        'fillType' => 'linear', //線性填充，類似漸變
                        'rotation' => 45, //漸變角度
                        'startColor' => [
                            'rgb' => '54AE54' //初始顏色
                        ],
                        //結束顏色，如果需要單一背景色，請和初始顏色保持一致
                        'endColor' => [
                            'argb' => '54AE54'
                        ]
                    ]
                ]);
            }
        ];
    }
}


class BuildingManagementController extends AppBaseController
{
    /** @var  BuildingManagementRepository */
    private $buildingManagementRepository;

    public function __construct(BuildingManagementRepository $buildingManagementRepo)
    {
        $this->buildingManagementRepository = $buildingManagementRepo;
    }

    /**
     * Display a listing of the BuildingManagement.
     *
     * @param BuildingManagementDataTable $buildingManagementDataTable
     * @return Response
     */
    public function index(BuildingManagementDataTable $buildingManagementDataTable)
    {
        return $buildingManagementDataTable->render('building_managements.index');
    }

    /**
     * Show the form for creating a new BuildingManagement.
     *
     * @return Response
     */
    public function create()
    {
        return view('building_managements.create');
    }

    /**
     * Store a newly created BuildingManagement in storage.
     *
     * @param CreateBuildingManagementRequest $request
     *
     * @return Response
     */
    public function store(CreateBuildingManagementRequest $request)
    {
        $input = $request->all();
        if (isset($input['same_address'])) {
            if ($input['same_address'] == 'on') {
                $input['residence_address_city'] = $input['address_city'];
                $input['residence_address_cityarea'] = $input['address_cityarea'];
                $input['residence_address_street'] = $input['address_street'];
                $input['residence_address_ln'] = $input['address_ln'];
                $input['residence_address_aly'] = $input['address_aly'];
                $input['residence_address_num'] = $input['address_num'];
                $input['residence_address_num_hyphen'] = $input['address_num_hyphen'];
            }
        }
        if (isset($input['pay_by_tenant'])) {
            if ($input['pay_by_tenant'] == 'on') {
                $input['manage_fee_month'] = 0;
            }
        }
        $input['Lessor_birthday'] = self::Format_TW_Date($input['Lessor_birthday']);
        $input['apply_date'] = self::Format_TW_Date($input['apply_date']);
        $input['h_info_completion_date'] = self::Format_TW_Date($input['h_info_completion_date']);
        $input['remark_1'] = self::Format_TW_Date($input['remark_1']);
        $input['files'] = $this->createFilesJson($request);

        $buildingManagement = $this->buildingManagementRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/buildingManagements.singular')]));

        return redirect(route('buildingManagements.index'));
    }

    /**
     * Display the specified BuildingManagement.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $buildingManagement = $this->buildingManagementRepository->find($id);

        if (empty($buildingManagement)) {
            Flash::error(__('messages.not_found', ['model' => __('models/buildingManagements.singular')]));

            return redirect(route('buildingManagements.index'));
        }

        return view('building_managements.edit')->with(['buildingManagement' => $buildingManagement, 'show' => true]);
    }

    /**
     * Show the form for editing the specified BuildingManagement.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $buildingManagement = $this->buildingManagementRepository->find($id);

        if (empty($buildingManagement)) {
            Flash::error(__('messages.not_found', ['model' => __('models/buildingManagements.singular')]));

            return redirect(route('buildingManagements.index'));
        }

        return view('building_managements.edit')->with('buildingManagement', $buildingManagement);
    }

    public function update(Request $request, $id)
    {
        $buildingManagement = $this->buildingManagementRepository->find($id);

        if (empty($buildingManagement)) {
            Flash::error(__('messages.not_found', ['model' => __('models/buildingManagements.singular')]));

            return redirect(route('buildingManagements.index'));
        }
        $input = $request->all();
        if (isset($input['pay_by_tenant'])) {
            if ($input['pay_by_tenant'] == 'on') {
                $input['manage_fee_month'] = 0;
            }
        }

        //        // 處理檔案json
        //        if ($buildingManagement['file_json'] != null && $input['file_json'] != null) {
        //            $database_file_json = json_decode($buildingManagement['file_json']);
        //            $new__file_json = json_decode($input['file_json']);
        //            foreach ($new__file_json as $key => $arr) {
        //                foreach ($arr as $index => $value) {
        //                    array_push($database_file_json->$key, $value);
        //                }
        //            }
        //            $input['file_json'] = json_encode($database_file_json);
        //        }

        $input['Lessor_birthday'] = isset($input['Lessor_birthday']) ? self::Format_TW_Date($input['Lessor_birthday']) : null;
        $input['apply_date'] = self::Format_TW_Date($input['apply_date']);
        $input['h_info_completion_date'] = self::Format_TW_Date($input['h_info_completion_date']);
        $input['remark_1'] = self::Format_TW_Date($input['remark_1']);
        $input['files'] = $this->createFilesJson($request, $buildingManagement);
        $buildingManagement = $this->buildingManagementRepository->update($input, $id);

        Flash::success(__('messages.updated', ['model' => __('models/buildingManagements.singular')]));

        return redirect(route('buildingManagements.index'));
    }

    /**
     * Remove the specified BuildingManagement from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $buildingManagement = $this->buildingManagementRepository->find($id);

        if (empty($buildingManagement)) {
            Flash::error(__('messages.not_found', ['model' => __('models/buildingManagements.singular')]));

            return redirect(route('buildingManagements.index'));
        }

        $this->buildingManagementRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/buildingManagements.singular')]));

        return redirect(route('buildingManagements.index'));
    }

    public function file_upload($file)
    {
        return Storage::put(storage_path('BuildingManagement'), $file);
    }

    public function import_build(Request $request)
    {
        return self::processExcel($request->file('import_file'));
    }

    public static function processExcel($file)
    {
        $results = [];

        $path = $file->getRealPath();
        $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
        $reader->setLoadSheetsOnly(["包租"]);
        $spreadsheet = $reader->load($path);
        $worksheet = $spreadsheet->getActiveSheet();
        $rows = $worksheet->toArray();
        foreach ($rows as $key => $row) {
            if ($key === 0 || $key === 1) {
                continue;
            }
            try {
                $find_by_num = BuildingManagement::where('num', $row[10])->first();
                if ($find_by_num) {
                    $results[] = [
                        'line' => $key + 1,
                        'case_num' => $row[10],
                        'result' => '重複輸入',
                    ];
                    continue;
                }
                $build = new BuildingManagement();

resources/views/building_managements/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid container-fixed-lg">
        <h3 class="page-title">
            @lang('models/buildingManagements.singular')
        </h3>
    </div>
    <div class="container-fluid container-fixed-lg">
        @include('adminlte-templates::common.errors')
        <div class="card card-transparent">
            <div class="card-body">
                <div class="row">
                    {!! Form::open(['route' => 'buildingManagements.store', 'enctype' => 'multipart/form-data']) !!}

                        @include('building_managements.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/building_managements/datatables_actions.blade.php
@php
    $b = \App\Models\BuildingManagement::where('id', $id)->first();

@endphp
<div class='btn-group'>
    <a href="/buildingManagements/export/{{$id}}" class='btn btn-default btn-xs' target="_blank">
        下載個人文件
    </a>
    @if($b->status == '已媒合' && auth()->user()->role == 'SALES')
    @elseif($b->status == '已媒合')
        <a href="{{ route('buildingManagements.edit', $id) }}" class='btn btn-default btn-xs'>
            <i class="glyphicon glyphicon-edit"></i>
        </a>
        {!! Form::open(['route' => ['buildingManagements.destroy', $id], 'method' => 'delete']) !!}
        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
            'type' => 'submit',
            'class' => 'btn btn-danger btn-xs',
            'onclick' => 'return confirm("'.__('crud.are_you_sure').'")'
        ]) !!}
        {!! Form::close() !!}
    @else
        <button id="updateStatus" type="button" class="btn btn-default" onclick="updateStatus()">轉已媒合</button>
        <a href="{{ route('buildingManagements.edit', $id) }}" class='btn btn-default btn-xs'>
            <i class="glyphicon glyphicon-edit"></i>
        </a>
        {!! Form::open(['route' => ['buildingManagements.destroy', $id], 'method' => 'delete']) !!}
        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
            'type' => 'submit',
            'class' => 'btn btn-danger btn-xs',
            'onclick' => 'return confirm("'.__('crud.are_you_sure').'")'
        ]) !!}
        {!! Form::close() !!}
            <script>
                function updateStatus() {
                    $.ajax({
                        type: "PATCH",
                        timeout: 60000,
                        url: "api/building_managements/" + {{$id}},
                        data: {
                            'status': '已媒合'
                        },
                        success: function (data) {
                            // Swal.fire({
                            //     icon: 'success',
                            //     title: '轉已媒合成功'
                            // })
                            location.reload();
                        },
                        error: function (data) {
                            Swal.fire({
                                icon: 'error',
                                title: '轉已媒合失敗',
                            })
                        },
                    });
                }
            </script>
    @endif
</div>

resources/views/building_managements/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid container-fixed-lg">
        <h3 class="page-title">@lang('models/buildingManagements.plural')</h3>
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px;z-index: 100" href="{{ route('buildingManagements.create') }}">@lang('crud.add_new')</a>
    </div>
    <div class="container-fluid container-fixed-lg">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                <form action="" id="importFile" method="post" enctype="multipart/form-data">
                    @csrf
                    <div id="app">
                        <button type="button" class="btn btn" onclick="select_file()">選擇檔案</button>
                        <input type="file" name="file" class="hide" id="import_file">
                        <input type="hidden" name="type" value="landlord">
                        <button class="btn btn" type="submit">導入</button>
                        <button type="button" class="btn btn" onclick="location.href='buildmag/download'">匯出匯款資料</button>
                    </div>
                </form>
                    @include('building_managements.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection
@push("scripts")
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script>
        $('#importFile').on('submit', function (e) {
            e.preventDefault();
            const formData = new FormData(this);
            $.ajax({
                type: "POST",
                timeout: 60000,
                url: "/api/batch_upload",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    const html =
                    `<table class="table table-responsive" style="max-height: 180px; overflow: auto">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Case</th>
                                <th scope="col">Result</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${ data.map(row => `
                                <tr>
                                    <th scope="row">${row.line}</th>
                                    <td>${row.case_num}</td>
                                    <td>${row.result}</td>
                                </tr>
                            `)}
                        </tbody>
                    </table>`
                    Swal.fire({
                        icon: 'success',
                        title: '匯入成功',
                        html,
                    })
                },
                error: function (data) {
                    Swal.fire({
                        icon: 'error',
                        title: '導入失敗 請確認檔案',
                    })
                },
            });
        })



        function select_file() {
            $('#import_file').val("");
            $('#import_file').click();
        }

    </script>
@endpush

resources/views/building_managements/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid   container-fixed-lg">
        <h3 class="page-title">
            @lang('models/buildingManagements.singular')
        </h3>
    </div>
    <div class="container-fluid   container-fixed-lg">
        <div class="card card-transparent">
            <div class="card-body">
                <div class="row" style="padding-left: 20px">
                    @include('building_managements.show_fields')
                    <a href="{{ route('buildingManagements.index') }}" class="btn btn-default">
                        @lang('crud.back')
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/building_managements/show_fields.blade.php
<div class="float_modal">
    {!! Form::model($buildingManagement, ['route' => ['buildingManagements.update', $buildingManagement->id], 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}

    @include('building_managements.fields')

    {!! Form::close() !!}
</div>
@push('scripts')
<script type="text/javascript">
    $(".float_modal input,.float_modal select").attr('readonly',1).attr('disabled','disabled')
</script>
@endpush

resources/views/building_managements/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush